### ISSUE TITLE
Wrong visualization of small numbers in an image

### ISSUE THREAD

**Issue by Alejandro-1996** [Biomedical-Imaging-Group/image-access#2]
When a number is given in scientific notation, the method visualize does not work properly. Moreover, some values are simply being erased. See example:

``` JavaScript
IPLabImageAccess {
  image: [ [ 3.061616997868383e-17, -0.5 ], [ 0.5, 3.061616997868383e-17 ] ],
  nx: 2,
  ny: 2,
  min: 0,
  max: 0,
  change_check: true
}
Result:
[[  3.06       ]
 [        3.06 ]]
```

While this does not hinder development, it is certainly urgent for the release of the labs

**Comment by TheUser0571** [comment]
It should now also work with scientific notation, very small and large numbers.
